'use server'

import prisma from '@/lib/prisma'
import { revalidatePath } from 'next/cache'
import { slugify } from '@/lib/utils'
import { productSchema } from '@/lib/validations'
import type { ActionResult, Product, ProductVariant } from '@/types'

export async function createProduct(formData: FormData): Promise<ActionResult<Product>> {
  try {
    const rawVariants = formData.get('variantsPayload') as string
    const variants = rawVariants ? JSON.parse(rawVariants) : []

    const compareAtPriceRaw = formData.get('compareAtPrice') as string
    const data = {
      name: formData.get('name') as string,
      description: formData.get('description') as string | null,
      price: parseFloat(formData.get('price') as string) || 0,
      compareAtPrice: compareAtPriceRaw ? parseFloat(compareAtPriceRaw) : null,
      brand: formData.get('brand') as string | null,
      categoryId: (formData.get('categoryId') as string) || null,
      isActive: formData.get('isActive') === 'on',
      isOffer: formData.get('isOffer') === 'on',
      variants,
    }

    const parsed = productSchema.safeParse(data)
    if (!parsed.success) {
      return { success: false, error: parsed.error.issues[0].message }
    }

    const { name, description, price, compareAtPrice, brand, categoryId, isActive, isOffer, variants: validatedVariants } = parsed.data
    
    // Generate unique slug
    let baseSlug = slugify(name)
    let slug = baseSlug
    let counter = 1
    while (await prisma.product.findUnique({ where: { slug } })) {
      slug = `${baseSlug}-${counter}`
      counter++
    }
    


    // Ensure variant SKUs are unique
    const skus = validatedVariants.map(v => v.sku)
    const duplicateSkus = skus.filter((sku, index) => skus.indexOf(sku) !== index)
    if (duplicateSkus.length > 0) {
      return { success: false, error: `Duplicate SKUs found: ${duplicateSkus.join(', ')}` }
    }

    const product = await prisma.product.create({
      data: {
        name,
        slug,
        description,
        price,
        compareAtPrice,
        brand,
        categoryId,
        isActive,
        isOffer,
        variants: {
          create: validatedVariants.map((v, index) => ({
            sku: v.sku,
            size: v.size,
            color: v.color,
            colorHex: v.colorHex,
            secondaryColorHex: v.secondaryColorHex,
            isAvailable: v.isAvailable,
            displayOrder: index,
            // id is auto-generated by Prisma
          }))
        }
      },
      include: { variants: true }
    })

    revalidatePath('/admin/products')
    revalidatePath('/')
    
    return { success: true, data: product as any }
  } catch (error) {
    console.error('Failed to create product:', error)
    return { success: false, error: 'Failed to create product.' }
  }
}

export async function updateProduct(id: string, formData: FormData): Promise<ActionResult<Product>> {
  try {
    const rawVariants = formData.get('variantsPayload') as string
    const variants = rawVariants ? JSON.parse(rawVariants) : []

    const compareAtPriceRaw = formData.get('compareAtPrice') as string
    const data = {
      name: formData.get('name') as string,
      description: formData.get('description') as string | null,
      price: parseFloat(formData.get('price') as string) || 0,
      compareAtPrice: compareAtPriceRaw ? parseFloat(compareAtPriceRaw) : null,
      brand: formData.get('brand') as string | null,
      categoryId: (formData.get('categoryId') as string) || null,
      isActive: formData.get('isActive') === 'on',
      isOffer: formData.get('isOffer') === 'on',
      variants,
    }

    const parsed = productSchema.safeParse(data)
    if (!parsed.success) {
      return { success: false, error: parsed.error.issues[0].message }
    }

    const { name, description, price, compareAtPrice, brand, categoryId, isActive, isOffer, variants: validatedVariants } = parsed.data
    
    // Generate unique slug
    let baseSlug = slugify(name)
    let slug = baseSlug
    let counter = 1
    while (await prisma.product.findFirst({ where: { slug, id: { not: id } } })) {
      slug = `${baseSlug}-${counter}`
      counter++
    }
    


    const skus = validatedVariants.map(v => v.sku)
    const duplicateSkus = skus.filter((sku, index) => skus.indexOf(sku) !== index)
    if (duplicateSkus.length > 0) {
      return { success: false, error: `Duplicate SKUs found: ${duplicateSkus.join(', ')}` }
    }

    // Get existing variants to diff
    const existingVariants = await prisma.productVariant.findMany({ where: { productId: id } })
    const incomingIds = validatedVariants.filter(v => v.id && !v.id.startsWith('temp_')).map(v => v.id)
    const variantsToDelete = existingVariants.filter((ev: ProductVariant) => !incomingIds.includes(ev.id))

    const product = await prisma.product.update({
      where: { id },
      data: {
        name,
        slug,
        description,
        price,
        compareAtPrice,
        brand,
        categoryId,
        isActive,
        isOffer,
        variants: {
          delete: variantsToDelete.map((v: ProductVariant) => ({ id: v.id })),
          upsert: validatedVariants.map((v, index) => ({
            where: { id: v.id?.startsWith('temp_') ? 'NEW_ID_FORCE_CREATE' : (v.id || 'NEW_ID_FORCE_CREATE') },
            create: {
              sku: v.sku, size: v.size, color: v.color, colorHex: v.colorHex, secondaryColorHex: v.secondaryColorHex, isAvailable: v.isAvailable, displayOrder: index
            },
            update: {
              sku: v.sku, size: v.size, color: v.color, colorHex: v.colorHex, secondaryColorHex: v.secondaryColorHex, isAvailable: v.isAvailable, displayOrder: index
            }
          }))
        }
      },
      include: { variants: true }
    })

    revalidatePath('/admin/products')
    revalidatePath(`/product/${slug}`)
    revalidatePath('/')

    return { success: true, data: product as any }
  } catch (error) {
    console.error('Failed to update product:', error)
    return { success: false, error: 'Failed to update product.' }
  }
}

export async function deleteProduct(id: string): Promise<ActionResult> {
  try {
    // Note: CASCADE deletes variants and images in DB per Prisma schema
    // Images in Supabase Storage should technically be deleted here too if we want a clean bucket.
    // For simplicity, we just delete the DB record right now. In production, we'd list and delete files.
    
    await prisma.product.delete({ where: { id } })

    revalidatePath('/admin/products')
    revalidatePath('/')
    
    return { success: true }
  } catch (error) {
    console.error('Failed to delete product:', error)
    return { success: false, error: 'Failed to delete product.' }
  }
}

export async function toggleProductActive(id: string): Promise<ActionResult<{ isActive: boolean }>> {
  try {
    const product = await prisma.product.findUnique({ where: { id } })
    if (!product) return { success: false, error: 'Not found' }

    const updated = await prisma.product.update({
      where: { id },
      data: { isActive: !product.isActive }
    })

    revalidatePath('/admin/products')
    revalidatePath(`/product/${updated.slug}`)
    revalidatePath('/')

    return { success: true, data: { isActive: updated.isActive } }
  } catch (error) {
     return { success: false, error: 'Failed to toggle product status' }
  }
}

export async function getProductBySlug(slug: string) {
  try {
    const product = await prisma.product.findUnique({
      where: { slug },
      include: {
        variants: {
          orderBy: { displayOrder: 'asc' },
        },
        images: {
          orderBy: { displayOrder: 'asc' },
        },
        category: true,
      },
    })

    if (!product || !product.isActive) {
      return null
    }

    return product
  } catch (error) {
    console.error(`Failed to fetch product with slug ${slug}:`, error)
    return null
  }
}

export async function updateProductOrder(items: { id: string; displayOrder: number }[]): Promise<ActionResult> {
  try {
    await prisma.$transaction(
      items.map((item) =>
        prisma.product.update({
          where: { id: item.id },
          data: { displayOrder: item.displayOrder },
        })
      )
    )
    revalidatePath('/admin/products')
    revalidatePath('/')
    return { success: true }
  } catch (error) {
    console.error('Failed to reorder products:', error)
    return { success: false, error: 'Failed to reorder products.' }
  }
}
